### ISSUE TITLE
Support GalacticOptim for unconstrained and bound constrained optimization

### ISSUE THREAD

**Issue by mohdibntarek** [JuliaNonconvex/Nonconvex.jl#28]
Would be nice to support GalacticOptim using the same interface here.

**Comment by jlperla** [comment]
You mean having GalacticOptim calling this interface?  Then that would be great!  And why not use this as an opportunity to get the galacticoptim interface to support all of these sorts of constraints?

**Comment by mohdibntarek** [comment]
Well there is https://github.com/SciML/GalacticOptim.jl/issues/123 so it's not clear which will call which. I might just specialize here in constrained optimization.

**Comment by jlperla** [comment]
Thanks.   Yeah, my dream is to only use galacticoptim as my universal interface for all optimizers (which is what its purpose) so it seams to make sense that it would call this package rather than the other way around.  But so far in the interfaces there, it hasn't had enough love on getting the constrained optimization interface correct - so maybe calling this package would be a good resaon to do so.

**Comment by mohdibntarek** [comment]
Closing this since GO/Optimization.jl wraps Nonconvex.
